In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [22]:
df=pd.read_csv('car_data.csv')
df.head(10)

name  year  selling_price  km_driven    fuel  \
0              Maruti 800 AC  2007          60000      70000  Petrol   
1   Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2       Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3     Datsun RediGO T Option  2017         250000      46000  Petrol   
4      Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   
5       Maruti Alto LX BSIII  2007         140000     125000  Petrol   
6  Hyundai Xcent 1.2 Kappa S  2016         550000      25000  Petrol   
7   Tata Indigo Grand Petrol  2014         240000      60000  Petrol   
8   Hyundai Creta 1.6 VTVT S  2015         850000      25000  Petrol   
9   Maruti Celerio Green VXI  2017         365000      78000     CNG   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner  
5  Individual       Manual   First Owner  
6  Individual       Manual   First Owner  
7  Individual       Manual  Second Owner  
8  Individual       Manual   First Owner  
9  Individual       Manual   First Owner

In [23]:
df['seller_type'].unique()

array(['Individual', 'Dealer', 'Trustmark Dealer'], dtype=object)

In [9]:
name_enc=LabelEncoder()
df['name'] = name_enc.fit_transform(df['name'])
fuel_enc=LabelEncoder()
df['fuel']=fuel_enc.fit_transform(df['fuel'])
seller_enc=LabelEncoder()
df['seller_type']=seller_enc.fit_transform(df['seller_type'])
transmission_enc=LabelEncoder()
df['transmission']=transmission_enc.fit_transform(df['transmission'])
owner_enc=LabelEncoder()
df['owner']=owner_enc.fit_transform(df['owner'])


rkd=df
rkd.head(10)

name  year  selling_price  km_driven  fuel  seller_type  transmission  \
0   775  2007          60000      70000     4            1             1   
1  1041  2007         135000      50000     4            1             1   
2   505  2012         600000     100000     1            1             1   
3   118  2017         250000      46000     4            1             1   
4   279  2014         450000     141000     1            1             1   
5   812  2007         140000     125000     4            1             1   
6   545  2016         550000      25000     4            1             1   
7  1256  2014         240000      60000     4            1             1   
8   390  2015         850000      25000     4            1             1   
9   834  2017         365000      78000     0            1             1   

   owner  
0      0  
1      0  
2      0  
3      0  
4      2  
5      0  
6      0  
7      2  
8      0  
9      0

In [24]:
rkd['seller_type'].unique()

array([1, 0, 2])

In [11]:

k=pd.read_csv('car_data.csv')

encoding=pf['name'].tolist()
namesli=k['name'].tolist()
namesli

NameError: name 'pf' is not defined

In [7]:
i=0
fin=[]
for x in encoding:
    po=[x,namesli[i]]
    fin.append(po)
    i=i+1

In [8]:
for x in fin:
    print(x[1])
    if x[1]=='Renault Duster 85PS Diesel RxE993':
        print(x[0])

Maruti 800 AC
Maruti Wagon R LXI Minor
Hyundai Verna 1.6 SX
Datsun RediGO T Option
Honda Amaze VX i-DTEC
Maruti Alto LX BSIII
Hyundai Xcent 1.2 Kappa S
Tata Indigo Grand Petrol
Hyundai Creta 1.6 VTVT S
Maruti Celerio Green VXI
Chevrolet Sail 1.2 Base
Tata Indigo Grand Petrol
Toyota Corolla Altis 1.8 VL CVT
Maruti 800 AC
Maruti Wagon R LXI Minor
Hyundai Verna 1.6 SX
Datsun RediGO T Option
Honda Amaze VX i-DTEC
Maruti Alto LX BSIII
Hyundai Xcent 1.2 Kappa S
Tata Indigo Grand Petrol
Hyundai Creta 1.6 VTVT S
Maruti Celerio Green VXI
Chevrolet Sail 1.2 Base
Tata Indigo Grand Petrol
Toyota Corolla Altis 1.8 VL CVT
Maruti Ciaz VXi Plus
Hyundai Venue SX Opt Diesel
Chevrolet Enjoy TCDi LTZ 7 Seater
Jaguar XF 2.2 Litre Luxury
Mercedes-Benz New C-Class 220 CDI AT
Maruti Vitara Brezza ZDi Plus AMT
Audi Q5 2.0 TDI
Honda City V MT
Tata Tigor 1.2 Revotron XT
Audi A6 2.0 TDI  Design Edition
Mercedes-Benz New C-Class C 220 CDI Avantgarde
Skoda Superb Ambition 2.0 TDI CR AT
Toyota Corolla Altis G AT
Toy

In [9]:
newfin=[]
for x in fin:
    if x not in newfin:
        newfin.append(x)
len(newfin)

1491

In [11]:
iop=open('nameset.csv','w')
ooo=0
for x in newfin:
    iop.write((str(x[0])+","+x[1]+"\n"))
    print(x)
    ooo=ooo+1
print(ooo)

[775, 'Maruti 800 AC']
[1041, 'Maruti Wagon R LXI Minor']
[505, 'Hyundai Verna 1.6 SX']
[118, 'Datsun RediGO T Option']
[279, 'Honda Amaze VX i-DTEC']
[812, 'Maruti Alto LX BSIII']
[545, 'Hyundai Xcent 1.2 Kappa S']
[1256, 'Tata Indigo Grand Petrol']
[390, 'Hyundai Creta 1.6 VTVT S']
[834, 'Maruti Celerio Green VXI']
[75, 'Chevrolet Sail 1.2 Base']
[1354, 'Toyota Corolla Altis 1.8 VL CVT']
[861, 'Maruti Ciaz VXi Plus']
[496, 'Hyundai Venue SX Opt Diesel']
[69, 'Chevrolet Enjoy TCDi LTZ 7 Seater']
[610, 'Jaguar XF 2.2 Litre Luxury']
[1093, 'Mercedes-Benz New C-Class 220 CDI AT']
[1021, 'Maruti Vitara Brezza ZDi Plus AMT']
[20, 'Audi Q5 2.0 TDI']
[313, 'Honda City V MT']
[1334, 'Tata Tigor 1.2 Revotron XT']
[12, 'Audi A6 2.0 TDI  Design Edition']
[1094, 'Mercedes-Benz New C-Class C 220 CDI Avantgarde']
[1197, 'Skoda Superb Ambition 2.0 TDI CR AT']
[1360, 'Toyota Corolla Altis G AT']
[1398, 'Toyota Innova 2.5 G (Diesel) 7 Seater']
[614, 'Jeep Compass 1.4 Sport Plus BSIV']
[1084, 'Mercedes

In [12]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
target=df['selling_price']
features=df[df.columns.difference(['selling_price'])]

In [13]:
xtr,xte,ytr,yte=train_test_split(features,target,test_size=0.3)

xte

fuel  km_driven  name  owner  seller_type  transmission  year
2797     1     151000   751      2            1             1  2014
531      1      75000  1417      0            1             1  2013
1383     1      90000   639      2            1             1  2010
1411     1      35000   539      0            1             1  2016
522      1      50000   992      0            0             1  2007
...    ...        ...   ...    ...          ...           ...   ...
1935     4      30000   655      2            1             1  2018
553      1      10000  1079      0            0             0  2018
101      4       9800  1088      0            0             0  2018
3555     1      75000   170      2            1             1  2014
33       4      14500   313      0            0             1  2018

[1302 rows x 7 columns]

In [14]:
yte

2797     600000
531      925000
1383     350000
1411     430000
522      225000
         ...   
1935     320000
553     3800000
101     4500000
3555     525000
33       930000
Name: selling_price, Length: 1302, dtype: int64

In [15]:
rf=RandomForestRegressor()

In [16]:
rf.fit(xtr,ytr)

RandomForestRegressor()

In [17]:
rf.score(xte,yte)

0.749267897691088

In [18]:
data={'fuel':[4],'km_driven':[5000],'name':[599],'owner':[0],'seller_type':[1],'transmission':[1],'year':[2010]}

In [19]:
dx=pd.DataFrame(data)

In [20]:
rf.predict(dx)

array([274800.])

In [192]:
from joblib import load

In [193]:
model=load('model.joblib')

In [194]:
model.predict(dx)

array([278950.])

In [165]:
from sklearn.linear_model import LinearRegression
X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.3, random_state=42)

op=LinearRegression()
op.fit(X_train,y_train)

LinearRegression()

In [166]:
op.score(X_test,y_test)

0.43929166443201084